/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

public class App {
    public static void main(String[] args) {
        Animal vetA[] = new Animal[20];

    vetA[0] = new Arara("Isa");
    vetA[1] = new Avestruz("Gustvo");
    vetA[2] = new Baleia("Willy");


        for (int i = 0; i < 3; i++) {

            System.out.println(vetA[i]);
            System.out.println(vetA[i].habilidade());
        }

    }


}
