/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

import java.util.ArrayList;
import java.util.List;

public class App {

    public static void main(String[] args) {

        Baralho baralho = new Baralho();


       // System.out.println(baralho.getCartas());



        System.out.println(baralho.getCartas());




       }


    }


