/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.Scanner;

public class App {
    public static void main(String[] args) {

        Scanner teclado = new Scanner(System.in);
        double[] notasP = new double[4];
        double[] notasPj = new double[2];
        int presenca;
        boolean mediaAprovacao = false;
        boolean aprovado = false;
        String msgAprovado;
        double somaP = 0;
        double somaPj = 0;

        System.out.println(" ===PROGRAMA PARA VERIFICAR APROVAÇAO===");
        System.out.println("Digite a nota 1 da prova (valores entre 0,0 a 10,0)");
        notasP[0] = teclado.nextDouble();
        System.out.println("Digite a nota 2 da prova (valores entre 0,0 a 10,0)");
        notasP[1] = teclado.nextDouble();
        System.out.println("Digite a nota 3 da prova (valores entre 0,0 a 10,0)");
        notasP[2] = teclado.nextDouble();
        System.out.println("Digite a nota 4 da prova (valores entre 0,0 a 10,0)");
        notasP[3] = teclado.nextDouble();
        System.out.println("Ótimo, agora as notas do projeto");
        System.out.println("Digite a nota 1 do projeto (valores entre 0,0 a 10,0)");
        notasPj[0] = teclado.nextDouble();
        System.out.println("Digite a nota 2 do projeto (valores entre 0,0 a 10,0)");
        notasPj[1] = teclado.nextDouble();
        System.out.println("Ótimo agora digite o percentual da presença");
        presenca = teclado.nextInt();



        for (double i = 0; i < notasP.length; i++) {
            somaP = somaP + notasP[(int) i];

        }
        for (double i = 0; i < notasPj.length; i++) {
            somaPj = somaPj + notasPj[(int) i];


        }

        double p =  (somaP/4.0);
        double pj = (somaPj/2.0);

        double mediaFiinal = Math.round(((p*3.0)+(pj*2.0))/5.0);

        if (somaPj >=12.0 && somaP >=24){
            mediaAprovacao = true;
        }else{
            mediaFiinal = 0.0;
        }

        if (mediaAprovacao && presenca >=75){
            aprovado = true;
            msgAprovado = "Aprovado";
        }else {
            msgAprovado = "Reprovado";
        }


        System.out.println("""
                P1- %.1f -  P2- %.1f  -  P3-%.1f  -  P4-%.1f -- PJ1-%.1f -  PJ2-%.1f
                                        
                Frequência =  %d%% 
                
                Media = %.1f
                =======================
                Status = %s
                """.formatted(notasP[0],notasP[1],notasP[2],notasP[3],notasPj[0],notasPj[1],presenca,mediaFiinal,msgAprovado
                ) );




















    }
}
