/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

public class App {

    public static void main(String[] args) {

        Personagem vetP[] = new Personagem[300];

        vetP[0] = new Aldeao();
        vetP[1] = new Arqueiro();
        vetP[2] = new Cavaleiro();

        for (int i = 0; i < 3; i++) {
            System.out.println(vetP[i].mover());
        }



    }
}
