/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        List<Lutador> lutadores = new ArrayList<>();

        lutadores.add(new Lutador("Pretty Boy","França",31,1.75,68.9,1,3,1));
        lutadores.add(new Lutador("Putscript","Brasil",29,1.68,57.8,14,2,3));
        lutadores.add(new Lutador("Snapshadow","EUA",35,1.65,80.9,12,2,1));
        lutadores.add(new Lutador("dead Code", "Australia",28,1.93,95.6,13,0,2));

        for (Lutador lutador : lutadores) {
         //   System.out.println(lutador.getCategoria());
       }
        System.out.println( lutadores.getFirst());
        Luta luta = new Luta();

       luta.lutar(lutadores.getFirst(),lutadores.getLast());


        System.out.println( lutadores.getFirst());
        luta.setDesafiado(lutadores.getFirst());
        luta.setDesafiante(lutadores.getLast());
        luta.lutar();
        System.out.println( lutadores.getFirst());






    }
}
